<?php

namespace Jose13\LaravelLineBotLottery\tests\EventsTypeTests\PostbackActionTypeTests;

use Exception;
use Jose13\LaravelLineBotLottery\Services\CrawlersService\TaiwanLottery\FiveThreeNine;

use Jose13\LaravelLineBotLottery\Services\Factory\TemplateTypeFactory;
use Jose13\LaravelLineBotLottery\Services\LineSupportEvents\EventsType\PostbackActionType\DateTimePickQuickAction;

use LINE\LINEBot;
use LINE\LINEBot\Event\BaseEvent;
use Tests\TestCase;
use Mockery;

class DateTimePickQuickActionTest extends TestCase
{

    /**
     * @var FiveThreeNine|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $fiveThreeNine;
    /**
     * @var LINEBot\Event\BaseEvent|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $baseEvent;

    /**
     * @var TemplateTypeFactory|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $templateTypeFactory;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->templateTypeFactory = Mockery::mock(TemplateTypeFactory::class);
        $this->fiveThreeNine = Mockery::mock(FiveThreeNine::class);
        $this->baseEvent = Mockery::mock(BaseEvent::class);

    }

    public function tearDown(): void
    {
        parent::tearDown();
        Mockery::close();
    }

    public function testGetResponseAndReturnNoBaLL()
    {

        $this->fiveThreeNine
            ->shouldReceive('getGameBallData')
            ->once()
            ->withAnyArgs()
            ->andReturn(
                [
                    [
                        '期別' => "999",
                        '開獎日期' => "110/08/02",
                        "最新累積頭獎金額" => "1000",
                        "本期頭獎單注獎金" => "500",
                    ]
                ]);

        $postbackArray = [
            "data" => "FiveThreeNine&full&26",
            "params" => [
                "date" => "2021-08-08"
            ]
        ];
        $this->baseEvent->shouldReceive('getPostbackParams')
            ->once()
            ->andReturn($postbackArray['params']);


        $this->baseEvent->shouldReceive('getPostbackData')
            ->once()
            ->andReturn($postbackArray['data']);



        $dateTimePickQuickAction = new DateTimePickQuickAction($this->baseEvent,$this->fiveThreeNine,$this->templateTypeFactory);
        $dateTimePickQuickActionResponse = $dateTimePickQuickAction->getResponse();

        $this->assertEquals('no Ball',$dateTimePickQuickActionResponse[0]);

    }
}
