<?php

namespace Jose13\LaravelLineBotLottery\tests\CrawlersServiceTests;


use Jose13\LaravelLineBotLottery\Services\CrawlersService\TaiwanLottery\FiveThreeNine;
use Tests\TestCase;

use Mockery;

class FiveThreeNineTest extends TestCase
{

    private FiveThreeNine $lottery;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lottery = new FiveThreeNine;
    }

    public function tearDown(): void
    {
        parent::tearDown();
        Mockery::close();
    }



    public function testGetMultiNewBallsByDatePick()
    {

        $returnBall = $this->lottery->getGameBallData(1, 106, 02);

        $this->assertArrayHasKey('期別', $returnBall[0]);
        $this->assertArrayHasKey('最新累積頭獎金額', $returnBall[0]);
        $this->assertArrayHasKey('開獎日期', $returnBall[0]);
        $this->assertArrayHasKey('落球順序', $returnBall[0]);
        $this->assertArrayHasKey('大小順序', $returnBall[0]);
        $this->assertArrayHasKey('本期中獎注數', $returnBall[0]);
        $this->assertArrayHasKey('本期頭獎單注獎金', $returnBall[0]);
        $this->assertArrayHasKey('貳獎獎金', $returnBall[0]);
        $this->assertArrayHasKey('參獎獎金', $returnBall[0]);
        $this->assertArrayHasKey('肆獎獎金', $returnBall[0]);


    }


}
