<?php

namespace Jose13\LaravelLineBotLottery\tests\EventsTypeTests;

use Exception;
use Jose13\LaravelLineBotLottery\Services\Factory\MessageEventTypeFactory;
use Jose13\LaravelLineBotLottery\Services\LineSupportEvents\EventsType\MessageEventType\TextResponse;
use Jose13\LaravelLineBotLottery\Services\LineSupportEvents\EventsType\TheMessageEvent;
use Jose13\LaravelLineBotLottery\Services\LineTemplateService\LineTemplateBuildService;
use LINE\LINEBot;
use LINE\LINEBot\Event\BaseEvent;
use LINE\LINEBot\MessageBuilder\TextMessageBuilder;
use LINE\LINEBot\Response;
use Mockery;
use Tests\TestCase;

class TheMessageEventTest extends TestCase
{
    /**
     * @var LineTemplateBuildService|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $lineTemplateBuildService;
    /**
     * @var BaseEvent|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $baseEvent;
    /**
     * @var LINEBot|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $lINEBot;

    /**
     * @var MessageEventTypeFactory|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $messageEventTypeFactory;
    /**
     * @var Response|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $response;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->lineTemplateBuildService = Mockery::mock(LineTemplateBuildService::class);
        $this->messageEventTypeFactory = Mockery::mock(MessageEventTypeFactory::class);
        $this->baseEvent = Mockery::mock(BaseEvent::class);
        $this->lINEBot = Mockery::mock(LINEBot::class);
        $this->response = Mockery::mock(Response::class);

    }

    public function tearDown(): void
    {
        parent::tearDown();
        Mockery::close();
    }

    public function testMessageEventAndGetReplyResultShouldBeErrorMessage()
    {
        $charts = 'UserChats';

        $this->baseEvent->shouldReceive('getText')
            ->once()
            ->andReturn('12345');

        $textResponse = Mockery::mock(new TextResponse($this->baseEvent,$charts));

        $this->messageEventTypeFactory->shouldReceive('makeTypeClass')
            ->once()
            ->with($this->baseEvent,$charts)
            ->andReturn($textResponse);


        $joinEvent = new TheMessageEvent(
            $this->baseEvent,
            $charts,
            $this->lINEBot,
            $this->lineTemplateBuildService,
            $this->messageEventTypeFactory);

        try {
            $replyResult = $joinEvent->getReplyResult();
        } catch (Exception $e) {
            $replyResult = $e->getMessage();
        }

        $this->assertEquals('this text content not support return',$replyResult);
    }




    public function testMessageEventAndGetReplyResultShouldBeSuccess()
    {
        $charts = 'UserChats';


        $this->baseEvent->shouldReceive('getReplyToken')
            ->once()
            ->andReturn('123');

        $this->baseEvent->shouldReceive('getText')
            ->once()
            ->andReturn('hello');

        $textResponse = Mockery::mock(new TextResponse($this->baseEvent,$charts));

        $this->messageEventTypeFactory->shouldReceive('makeTypeClass')
            ->once()
            ->with($this->baseEvent,$charts)
            ->andReturn($textResponse);

        $this->lineTemplateBuildService->shouldReceive('createTextMessageBuilder')
            ->once()
            ->andReturn(new TextMessageBuilder('hi'));
        $this->lINEBot->shouldReceive('replyMessage')
            ->once()
            ->andReturn($this->response);

        $this->response->shouldReceive('isSucceeded')
            ->once()
            ->andReturn('success');

        $theMessageEvent = new TheMessageEvent(
            $this->baseEvent,
            $charts,
            $this->lINEBot,
            $this->lineTemplateBuildService,
            $this->messageEventTypeFactory
        );

        try {
            $replyResult = $theMessageEvent->getReplyResult();
        } catch (Exception $e) {
            $replyResult = $e->getMessage();
        }
        $this->assertEquals('success',$replyResult);
    }
}
