<?php

namespace Jose13\LaravelLineBotLottery\tests\EventsTypeTests\MessageEventTypeTests;


use Jose13\LaravelLineBotLottery\Services\LineSupportEvents\EventsType\MessageEventType\TextResponse;
use LINE\LINEBot\Event\BaseEvent;
use Mockery;
use Tests\TestCase;

class TextResponseTest extends TestCase
{
    /**
     * @var TextResponse|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $textResponse;
    /**
     * @var BaseEvent|Mockery\LegacyMockInterface|Mockery\MockInterface
     */
    private $BaseEvent;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->BaseEvent = Mockery::mock(BaseEvent::class);

    }

    public function tearDown(): void
    {
        parent::tearDown();
        Mockery::close();
    }


    public function test_GetResponse_input_hello_then_get_hi()
    {
        $this->BaseEvent->shouldReceive('getText')
            ->once()
            ->andReturn('hello');

        $textResponse = new TextResponse($this->BaseEvent,'UserChats');

        $response = $textResponse->getResponse();

        $this->assertSame('hi', $response);
    }

}
